//********************************静态页面用，程序猿请忽略**************************************
document.writeln("<!-- 脚步菜单开始 -->");
document.writeln("    <div class=\"w footerNav clearFix\">");
document.writeln("        <dl>");
document.writeln("            <dt>新手指南</dt>");
document.writeln("            <dd><a href=\"#\">登录/注册账户</a></dd>");
document.writeln("            <dd><a href=\"#\">如何找回密码</a></dd>");
document.writeln("            <dd><a href=\"#\">网上订购流程</a></dd>");
document.writeln("            <dd><a href=\"#\">会员级别与优惠</a></dd>");
// document.writeln("            <dd><a href=\"#\">优惠券使用说明</a></dd>");
document.writeln("        </dl>");
document.writeln("        <dl>");
document.writeln("            <dt>付款与配送</dt>");
document.writeln("            <dd><a href=\"#\">在线支付</a></dd>");
document.writeln("            <dd><a href=\"#\">发票制度说明</a></dd>");
document.writeln("            <dd><a href=\"#\">到店自提说明</a></dd>");
document.writeln("            <dd><a href=\"#\">配送范围及时间</a></dd>");
document.writeln("            <dd><a href=\"#\">配送政策</a></dd>");
document.writeln("        </dl>");
document.writeln("        <dl>");
document.writeln("            <dt>售后服务</dt>");
document.writeln("            <dd><a href=\"#\">如何办理退款</a></dd>");
document.writeln("            <dd><a href=\"#\">退换货说明</a></dd>");
document.writeln("            <dd><a href=\"#\">包类免费养护政策</a></dd>");
document.writeln("            <dd><a href=\"#\">售后服务保养手册</a></dd>");
document.writeln("            <dd><a href=\"#\">鉴定服务</a></dd>");
document.writeln("        </dl>");
document.writeln("        <dl>");
document.writeln("            <dt>关于博纳优品</dt>");
document.writeln("            <dd><a href=\"#\">免责声明</a></dd>");
document.writeln("            <dd><a href=\"#\">关于博纳优品</a></dd>");
document.writeln("            <dd><a href=\"#\">联系我们</a></dd>");
// document.writeln("            <dd><a href=\"#\">北京丰联广场店</a></dd>");
document.writeln("        </dl>");
document.writeln("        <dl style='width:200px;'>");
document.writeln("            <dt>客服电话：010-64898139</dt>");
document.writeln("            <dd>欢迎关注【博纳优品】微信订阅号</dd>");
document.writeln("        </dl>");
document.writeln("        <div style='margin-top: -17px;float: left;'>");
document.writeln("            <img src='css/images/erweima.jpg' style='width:100px;float:left;' />");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!-- 脚步菜单结束 -->");
document.writeln("    <!-- 通栏广告图片开始 -->");
document.writeln("    <div class=\"footer_adImg\"></div>");
document.writeln("    <!-- 通栏广告图片结束 -->");
document.writeln("    <!-- 链接和版权开始 -->");
document.writeln("    <p class=\"footer_copy txt_center mt20 \">");
document.writeln("        <a class=\"textColor000\" href=\"#\">BONAUPIN 网</a>|");
document.writeln("        <a class=\"textColor000\" href=\"#\">奢侈品养护</a>");
document.writeln("    </p>");
document.writeln("    <p class=\"footer_copy txt_center  \">");
document.writeln("        <a class=\"textColor000\" href=\"#\">加入BONAUPIN</a>|");
document.writeln("        <a class=\"textColor000\" href=\"#\">联系我们</a>｜");
document.writeln("        <a class=\"textColor000\" href=\"#\">关于BONAUPIN</a>｜");
document.writeln("        <a class=\"textColor000\" href=\"#\">帮助中心</a>｜");
document.writeln("        <a class=\"textColor000\" href=\"#\">BONAUPIN微博</a>｜");
document.writeln("        <a class=\"textColor000\" href=\"#\">友情链接</a>");
document.writeln("    </p>");
document.writeln("    <p class=\"footer_copy txt_center  \">");
document.writeln("        <span>营业执照注册号11010211888762</span>|");
document.writeln("        <span>京公安备11010102001392</span>|");
document.writeln("        <span>京ICP证110119</span>");
document.writeln("    </p>");
document.writeln("    <p class=\"footer_copy txt_center  \">");
document.writeln("        <span>京ICP备09084709号-3</span>|");
document.writeln("        <span>ISO9001中国质量管理体系认证</span>");
document.writeln("    </p>");
document.writeln("    <p class=\"footer_icpImg txt_center\">");
document.writeln("        <a class=\"footer_icpImg1\" href=\"#\"></a>");
document.writeln("        <a class=\"footer_icpImg2\" href=\"#\"></a>");
document.writeln("        <a class=\"footer_icpImg3\" href=\"#\"></a>");
document.writeln("    </p>");
document.writeln("    <!-- 链接和版权结束 -->");