//********************************静态页面用，程序猿请忽略**************************************
document.writeln("   <div class=\" headerBar\">");
document.writeln("        <!-- 头部菜单开始 -->");
document.writeln("        <div class=\"learFix\">");

document.writeln("        <div class=\"w  s\">");

document.writeln("            <a class=\"headerBar_l\" href=\"javascript:;\"><i class=\"icon\"></i>收藏BONAUPIN</a>");
document.writeln("            <ul class=\"headerBar_r\">");
document.writeln("                <li>欢迎光临BONAUPIN</li>");
document.writeln("                <li><a href=\"javascript:;\">请登录</a></li>");
document.writeln("                <li class=\"bnt_regist\"><a class=\"headerBar_line \" href=\"javascript:;\">免费注册</a></li>");
document.writeln("                <li><a href=\"个人中心_userCenter.html\">我的订单</a></li>");
document.writeln("                <li class=\"kw\">");
document.writeln("                    <a class=\"headerBar_line\" href=\"javascript:;\"><i class=\"icon\"></i>客户服务</a>");
document.writeln("                    <dl>");
document.writeln("                        <dd><a href=\"javascript:;\">养护中心</a></dd>");
document.writeln("                        <dd><a href=\"javascript:;\">帮助中心</a></dd>");
document.writeln("                        <dd><a href=\"javascript:;\">投诉中心</a></dd>");
document.writeln("                        <dd class=\"kw_tel lastBottom\">贵宾专线<br />");
document.writeln("                            400-733-6667</dd>");
document.writeln("                    </dl>");
document.writeln("                </li>");
document.writeln("                <li class=\"cart\"><a href=\"javascript:;\"><i class=\"icon\"></i>购物车(88)</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");

document.writeln("        </div>");

document.writeln("        <!-- 头部菜单结束 -->");
document.writeln("");
document.writeln("    </div>");
document.writeln("    <!-- 搜索区域开始 -->");
document.writeln("    <div class=\"w seachBox\">");
document.writeln("        <a class=\"seachBox_logo fl\" href=\"首页_index.html\"></a>");
document.writeln("        <!--searchForm-->");
document.writeln("        <div class=\"searchForm fl\">");
document.writeln("            <div class=\"searchTips\"></div>");
document.writeln("            <input type=\"text\" class=\"SearchKey input_search_key\" id=\"gover_search_key\" />");
document.writeln("            <a class=\"SearchButton \" href=\"商品列表页_proList.html\">搜索</a>");
document.writeln("        </div>");
document.writeln("        <!--end searchForm-->");
document.writeln("    </div>");
document.writeln("    <!-- 搜索区域结束 -->");
document.writeln("    <!-- 导航开始 -->");
document.writeln("    <ul class=\"w nav \">");
document.writeln("        <!-- 一级hover -->");
document.writeln("        <li class=\"nav_li \">");
document.writeln("            <a class=\"nav_level1 chooseAdd\" href=\"商品列表页_proList.html\">全部优品<i class=\"icon icon_nav_level1\"></i></a>");
document.writeln("            <!-- 二级show -->");
document.writeln("            <ul class=\"nav_level2 \">");
document.writeln("                <li class=\"nav_level2_li \">");
document.writeln("                    <!-- 二级内容 -->");
document.writeln("                    <div class=\"level2Box \">");
document.writeln("                        <div class=\"zhou\"><a href=\"javascript:;\">箱包</a><i class=\"icon icon_nav\"></i></div>");
document.writeln("                        <div class=\"zhou_more\"><a href=\"javascript:;\">单肩包</a><a href=\"javascript:;\">手提包</a><a href=\"javascript:;\">斜挎包</a></div>");
document.writeln("                    </div>");
document.writeln("                    <!-- 三级内容 show-->");
document.writeln("                    <div class=\"level3Box \">");
document.writeln("                        <dl>");
document.writeln("                            <dt>分类</dt>");
document.writeln("                            <dd><a href=\"#\" title=\"男士腕表\">男士腕表</a><a href=\"#\" title=\"女士腕表\">女士腕表</a><a href=\"#\" title=\"机械腕表\">机械腕表</a><a href=\"#\" title=\"石英腕表\">石英腕表</a></dd>");
document.writeln("                        </dl>");
document.writeln("                        <dl>");
document.writeln("                            <dt>品牌</dt>");
document.writeln("                            <dd><a href=\"#\" title=\"百达翡丽\">百达翡丽</a><a href=\"#\" title=\"江诗丹顿\">江诗丹顿</a><a href=\"#\" title=\"宝珀\">宝珀</a><a href=\"#\" title=\"百达翡丽\">百达翡丽</a><a href=\"#\" title=\"江诗丹顿\">江诗丹顿</a><a href=\"#\" title=\"宝珀\">宝珀</a><a href=\"#\" title=\"百达翡丽\">百达翡丽</a><a href=\"#\" title=\"江诗丹顿\">江诗丹顿</a><a href=\"#\" title=\"宝珀\">宝珀</a><a href=\"#\" title=\"百达翡丽\">百达翡丽</a><a href=\"#\" title=\"江诗丹顿\">江诗丹顿</a><a href=\"#\" title=\"宝珀\">宝珀</a><a href=\"#\" title=\"百达翡丽\">百达翡丽</a><a href=\"#\" title=\"江诗丹顿\">江诗丹顿</a><a href=\"#\" title=\"宝珀\">宝珀</a><a href=\"#\" title=\"百达翡丽\">百达翡丽</a><a href=\"#\" title=\"江诗丹顿\">江诗丹顿</a><a href=\"#\" title=\"宝珀\">宝珀</a></dd>");
document.writeln("                        </dl>");
document.writeln("                        <dl class=\"lastBottom\">");
document.writeln("                            <dt>热词</dt>");
document.writeln("                            <dd><a href=\"#\" title=\"百达翡丽\">百达翡丽</a><a href=\"#\" title=\"江诗丹顿\">江诗丹顿</a><a href=\"#\" title=\"宝珀\">宝珀</a><a href=\"#\" title=\"百达翡丽\">百达翡丽</a><a href=\"#\" title=\"江诗丹顿\">江诗丹顿</a><a href=\"#\" title=\"宝珀\">宝珀</a></dd>");
document.writeln("                        </dl>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\"nav_level2_li \">");
document.writeln("                    <!-- 二级内容 -->");
document.writeln("                    <div class=\"level2Box\">");
document.writeln("                        <div class=\"zhou\"><a href=\"javascript:;\">配饰</a><i class=\"icon icon_nav\"></i></div>");
document.writeln("                        <div class=\"zhou_more\"><a href=\"javascript:;\">丝巾</a><a href=\"javascript:;\">领带</a><a href=\"javascript:;\">帽子</a></div>");
document.writeln("                    </div>");
document.writeln("                    <!-- 三级内容 -->");
document.writeln("                    <div class=\"level3Box \">2222</div>");
document.writeln("                </li>");
document.writeln("                <li class=\"nav_level2_li\">");
document.writeln("                    <!-- 二级内容 -->");
document.writeln("                    <div class=\"level2Box\">");
document.writeln("                        <div class=\"zhou\"><a href=\"javascript:;\">配饰</a><i class=\"icon icon_nav\"></i></div>");
document.writeln("                        <div class=\"zhou_more\"><a href=\"javascript:;\">丝巾</a><a href=\"javascript:;\">领带</a><a href=\"javascript:;\">帽子</a></div>");
document.writeln("                    </div>");
document.writeln("                    <!-- 三级内容 -->");
document.writeln("                    <div class=\"level3Box\">333333</div>");
document.writeln("                </li>");
document.writeln("                <li class=\"nav_level2_li\">");
document.writeln("                    <!-- 二级内容 -->");
document.writeln("                    <div class=\"level2Box\">");
document.writeln("                        <div class=\"zhou\"><a href=\"javascript:;\">配饰</a><i class=\"icon icon_nav\"></i></div>");
document.writeln("                        <div class=\"zhou_more\"><a href=\"javascript:;\">丝巾</a><a href=\"javascript:;\">领带</a><a href=\"javascript:;\">帽子</a></div>");
document.writeln("                    </div>");
document.writeln("                    <!-- 三级内容 -->");
document.writeln("                    <div class=\"level3Box\">444444</div>");
document.writeln("                </li>");
document.writeln("                <li class=\"nav_level2_li\">");
document.writeln("                    <!-- 二级内容 -->");
document.writeln("                    <div class=\"level2Box\">");
document.writeln("                        <div class=\"zhou\"><a href=\"javascript:;\">配饰</a><i class=\"icon icon_nav\"></i></div>");
document.writeln("                        <div class=\"zhou_more\"><a href=\"javascript:;\">丝巾</a><a href=\"javascript:;\">领带</a><a href=\"javascript:;\">帽子</a></div>");
document.writeln("                    </div>");
document.writeln("                    <!-- 三级内容 -->");
document.writeln("                    <div class=\"level3Box\">55555</div>");
document.writeln("                </li>");
document.writeln("                <li class=\"nav_level2_li \">");
document.writeln("                    <!-- 二级内容 -->");
document.writeln("                    <div class=\"level2Box lastBottom\">");
document.writeln("                        <div class=\"zhou\"><a href=\"javascript:;\">配饰</a><i class=\"icon icon_nav\"></i></div>");
document.writeln("                        <div class=\"zhou_more\"><a href=\"javascript:;\">丝巾</a><a href=\"javascript:;\">领带</a><a href=\"javascript:;\">帽子</a></div>");
document.writeln("                    </div>");
document.writeln("                    <!-- 三级内容 -->");
document.writeln("                    <div class=\"level3Box\">66666</div>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("        <li class=\"nav_li\"><a class=\"nav_level1\" href=\"首页_index.html\">首页</a></li>");
document.writeln("        <li class=\"nav_li\"><a class=\"nav_level1\" href=\"首页_index.html\">精品推荐</a></li>");
document.writeln("        <li class=\"nav_li\"><a class=\"nav_level1\" href=\"首页_index.html\">美丽佳人</a></li>");
document.writeln("        <li class=\"nav_li\"><a class=\"nav_level1\" href=\"首页_index.html\">优雅男士</a></li>");
document.writeln("        <li class=\"nav_li\"><a class=\"nav_level1\" href=\"首页_index.html\">优品课堂</a></li>");
document.writeln("        <li class=\"nav_li\"><a class=\"nav_level1\" href=\"首页_index.html\">限量定制众筹</a></li>");
document.writeln("    </ul>");
document.writeln("    <!-- 导航结束 -->");